package com.ibm.cics.genapp.records;
import com.ibm.jzos.fields.*;

// Generated by com.ibm.jzos.recordgen.cobol.RecordClassGenerator on Thu Nov 05 00:49:15 GMT 2015

public class GenAppCommarea {
	protected static CobolDatatypeFactory factory = new CobolDatatypeFactory();
	static { factory.setStringTrimDefault(false); } 

	/** <pre>
	 01  DFHCOMMAREA. </pre> */
	public static final int DFHCOMMAREA_In__len = 32500; 

	/** <pre>
	       COPY LGCMAREA.
	******************************************************************
	*                                                                *
	* LICENSED MATERIALS - PROPERTY OF IBM                           *
	*                                                                *
	* "RESTRICTED MATERIALS OF IBM"                                  *
	*                                                                *
	* CB12                                                           *
	*                                                                *
	* (C) COPYRIGHT IBM CORP. 2011, 2013 ALL RIGHTS RESERVED         *
	*                                                                *
	* US GOVERNMENT USERS RESTRICTED RIGHTS - USE, DUPLICATION,      *
	* OR DISCLOSURE RESTRICTED BY GSA ADP SCHEDULE                   *
	* CONTRACT WITH IBM CORPORATION                                  *
	*                                                                *
	*                                                                *
	*               COPYBOOK for COMMAREA structure                  *
	*                                                                *
	*   This commarea can be used for all functions                  *
	*                                                                *
	*                                                                *
	*                                                                *
	******************************************************************
	     03 CA-REQUEST-ID            PIC X(6). </pre> */
	protected static final StringField CA_REQUEST_ID = factory.getStringField(6);

	/** <pre>
	     03 CA-RETURN-CODE           PIC 9(2). </pre> */
	protected static final ExternalDecimalAsIntField CA_RETURN_CODE = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	     03 CA-CUSTOMER-NUM          PIC 9(10). </pre> */
	protected static final ExternalDecimalAsLongField CA_CUSTOMER_NUM = factory.getExternalDecimalAsLongField(10, false, false, false, false);

	/** <pre>
	     03 CA-REQUEST-SPECIFIC      PIC X(32482). </pre> */
	protected static final StringField CA_REQUEST_SPECIFIC = factory.getStringField(32482);

	/** <pre>
	*    Fields used in INQ All and ADD customer
	     03 CA-CUSTOMER-REQUEST REDEFINES CA-REQUEST-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_REQUEST_SPECIFIC.getOffset()); } 
	public static final int CA_CUSTOMER_REQUEST_len = 32482; 
	public static final int CA_CUSTOMER_REQUEST_offset = factory.getOffset();

	/** <pre>
	        05 CA-FIRST-NAME         PIC X(10). </pre> */
	protected static final StringField CA_FIRST_NAME = factory.getStringField(10);

	/** <pre>
	        05 CA-LAST-NAME          PIC X(20). </pre> */
	protected static final StringField CA_LAST_NAME = factory.getStringField(20);

	/** <pre>
	        05 CA-DOB                PIC X(10). </pre> */
	protected static final StringField CA_DOB = factory.getStringField(10);

	/** <pre>
	        05 CA-HOUSE-NAME         PIC X(20). </pre> */
	protected static final StringField CA_HOUSE_NAME = factory.getStringField(20);

	/** <pre>
	        05 CA-HOUSE-NUM          PIC X(4). </pre> */
	protected static final StringField CA_HOUSE_NUM = factory.getStringField(4);

	/** <pre>
	        05 CA-POSTCODE           PIC X(8). </pre> */
	protected static final StringField CA_POSTCODE = factory.getStringField(8);

	/** <pre>
	        05 CA-NUM-POLICIES       PIC 9(3). </pre> */
	protected static final ExternalDecimalAsIntField CA_NUM_POLICIES = factory.getExternalDecimalAsIntField(3, false, false, false, false);

	/** <pre>
	        05 CA-PHONE-MOBILE       PIC X(20). </pre> */
	protected static final StringField CA_PHONE_MOBILE = factory.getStringField(20);

	/** <pre>
	        05 CA-PHONE-HOME         PIC X(20). </pre> */
	protected static final StringField CA_PHONE_HOME = factory.getStringField(20);

	/** <pre>
	        05 CA-EMAIL-ADDRESS      PIC X(100). </pre> */
	protected static final StringField CA_EMAIL_ADDRESS = factory.getStringField(100);

	/** <pre>
	        05 CA-POLICY-DATA        PIC X(32267). </pre> */
	protected static final StringField CA_POLICY_DATA = factory.getStringField(32267);
	static { factory.popOffset(); } 

	/** <pre>
	*    Fields used in Customer security call
	     03 CA-CUSTSECR-REQUEST REDEFINES CA-REQUEST-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_REQUEST_SPECIFIC.getOffset()); } 
	public static final int CA_CUSTSECR_REQUEST_len = 32482; 
	public static final int CA_CUSTSECR_REQUEST_offset = factory.getOffset();

	/** <pre>
	        05 CA-CUSTSECR-PASS      PIC X(32). </pre> */
	protected static final StringField CA_CUSTSECR_PASS = factory.getStringField(32);

	/** <pre>
	        05 CA-CUSTSECR-COUNT     PIC X(4). </pre> */
	protected static final StringField CA_CUSTSECR_COUNT = factory.getStringField(4);

	/** <pre>
	        05 CA-CUSTSECR-STATE     PIC X. </pre> */
	protected static final StringField CA_CUSTSECR_STATE = factory.getStringField(1);

	/** <pre>
	        05 CA-CUSTSECR-DATA      PIC X(32445). </pre> */
	protected static final StringField CA_CUSTSECR_DATA = factory.getStringField(32445);
	static { factory.popOffset(); } 

	/** <pre>
	*    Fields used in INQ, UPD, ADD & DELETE policy
	     03 CA-POLICY-REQUEST REDEFINES CA-REQUEST-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_REQUEST_SPECIFIC.getOffset()); } 
	public static final int CA_POLICY_REQUEST_len = 32482; 
	public static final int CA_POLICY_REQUEST_offset = factory.getOffset();

	/** <pre>
	        05 CA-POLICY-NUM         PIC 9(10). </pre> */
	protected static final ExternalDecimalAsLongField CA_POLICY_NUM = factory.getExternalDecimalAsLongField(10, false, false, false, false);

	/** <pre>
	*       Common policy details
	        05 CA-POLICY-COMMON. </pre> */
	public static final int CA_POLICY_COMMON_len = 72; 
	public static final int CA_POLICY_COMMON_offset = factory.getOffset();

	/** <pre>
	           07 CA-ISSUE-DATE      PIC X(10). </pre> */
	protected static final StringField CA_ISSUE_DATE = factory.getStringField(10);

	/** <pre>
	           07 CA-EXPIRY-DATE     PIC X(10). </pre> */
	protected static final StringField CA_EXPIRY_DATE = factory.getStringField(10);

	/** <pre>
	           07 CA-LASTCHANGED     PIC X(26). </pre> */
	protected static final StringField CA_LASTCHANGED = factory.getStringField(26);

	/** <pre>
	           07 CA-BROKERID        PIC 9(10). </pre> */
	protected static final ExternalDecimalAsLongField CA_BROKERID = factory.getExternalDecimalAsLongField(10, false, false, false, false);

	/** <pre>
	           07 CA-BROKERSREF      PIC X(10). </pre> */
	protected static final StringField CA_BROKERSREF = factory.getStringField(10);

	/** <pre>
	           07 CA-PAYMENT         PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField CA_PAYMENT = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	        05 CA-POLICY-SPECIFIC    PIC X(32400). </pre> */
	protected static final StringField CA_POLICY_SPECIFIC = factory.getStringField(32400);

	/** <pre>
	*       Endowment policy description
	        05 CA-ENDOWMENT REDEFINES CA-POLICY-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_POLICY_SPECIFIC.getOffset()); } 
	public static final int CA_ENDOWMENT_len = 32400; 
	public static final int CA_ENDOWMENT_offset = factory.getOffset();

	/** <pre>
	           07 CA-E-WITH-PROFITS    PIC X. </pre> */
	protected static final StringField CA_E_WITH_PROFITS = factory.getStringField(1);

	/** <pre>
	           07 CA-E-EQUITIES        PIC X. </pre> */
	protected static final StringField CA_E_EQUITIES = factory.getStringField(1);

	/** <pre>
	           07 CA-E-MANAGED-FUND    PIC X. </pre> */
	protected static final StringField CA_E_MANAGED_FUND = factory.getStringField(1);

	/** <pre>
	           07 CA-E-FUND-NAME       PIC X(10). </pre> */
	protected static final StringField CA_E_FUND_NAME = factory.getStringField(10);

	/** <pre>
	           07 CA-E-TERM            PIC 99. </pre> */
	protected static final ExternalDecimalAsIntField CA_E_TERM = factory.getExternalDecimalAsIntField(2, false, false, false, false);

	/** <pre>
	           07 CA-E-SUM-ASSURED     PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField CA_E_SUM_ASSURED = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	           07 CA-E-LIFE-ASSURED    PIC X(31). </pre> */
	protected static final StringField CA_E_LIFE_ASSURED = factory.getStringField(31);

	/** <pre>
	           07 CA-E-PADDING-DATA    PIC X(32348). </pre> */
	protected static final StringField CA_E_PADDING_DATA = factory.getStringField(32348);
	static { factory.popOffset(); } 

	/** <pre>
	*       House policy description
	        05 CA-HOUSE REDEFINES CA-POLICY-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_POLICY_SPECIFIC.getOffset()); } 
	public static final int CA_HOUSE_len = 32400; 
	public static final int CA_HOUSE_offset = factory.getOffset();

	/** <pre>
	           07 CA-H-PROPERTY-TYPE   PIC X(15). </pre> */
	protected static final StringField CA_H_PROPERTY_TYPE = factory.getStringField(15);

	/** <pre>
	           07 CA-H-BEDROOMS        PIC 9(3). </pre> */
	protected static final ExternalDecimalAsIntField CA_H_BEDROOMS = factory.getExternalDecimalAsIntField(3, false, false, false, false);

	/** <pre>
	           07 CA-H-VALUE           PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_H_VALUE = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-H-HOUSE-NAME      PIC X(20). </pre> */
	protected static final StringField CA_H_HOUSE_NAME = factory.getStringField(20);

	/** <pre>
	           07 CA-H-HOUSE-NUMBER    PIC X(4). </pre> */
	protected static final StringField CA_H_HOUSE_NUMBER = factory.getStringField(4);

	/** <pre>
	           07 CA-H-POSTCODE        PIC X(8). </pre> */
	protected static final StringField CA_H_POSTCODE = factory.getStringField(8);

	/** <pre>
	           07 CA-H-FILLER          PIC X(32342). </pre> */
	protected static final StringField CA_H_FILLER = factory.getStringField(32342);
	static { factory.popOffset(); } 

	/** <pre>
	*       Motor policy description
	        05 CA-MOTOR REDEFINES CA-POLICY-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_POLICY_SPECIFIC.getOffset()); } 
	public static final int CA_MOTOR_len = 32400; 
	public static final int CA_MOTOR_offset = factory.getOffset();

	/** <pre>
	           07 CA-M-MAKE            PIC X(15). </pre> */
	protected static final StringField CA_M_MAKE = factory.getStringField(15);

	/** <pre>
	           07 CA-M-MODEL           PIC X(15). </pre> */
	protected static final StringField CA_M_MODEL = factory.getStringField(15);

	/** <pre>
	           07 CA-M-VALUE           PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField CA_M_VALUE = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	           07 CA-M-REGNUMBER       PIC X(7). </pre> */
	protected static final StringField CA_M_REGNUMBER = factory.getStringField(7);

	/** <pre>
	           07 CA-M-COLOUR          PIC X(8). </pre> */
	protected static final StringField CA_M_COLOUR = factory.getStringField(8);

	/** <pre>
	           07 CA-M-CC              PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_M_CC = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-M-MANUFACTURED    PIC X(10). </pre> */
	protected static final StringField CA_M_MANUFACTURED = factory.getStringField(10);

	/** <pre>
	           07 CA-M-PREMIUM         PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField CA_M_PREMIUM = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	           07 CA-M-ACCIDENTS       PIC 9(6). </pre> */
	protected static final ExternalDecimalAsIntField CA_M_ACCIDENTS = factory.getExternalDecimalAsIntField(6, false, false, false, false);

	/** <pre>
	           07 CA-M-FILLER          PIC X(32323). </pre> */
	protected static final StringField CA_M_FILLER = factory.getStringField(32323);
	static { factory.popOffset(); } 

	/** <pre>
	*       Commercial policy description
	        05 CA-COMMERCIAL REDEFINES CA-POLICY-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_POLICY_SPECIFIC.getOffset()); } 
	public static final int CA_COMMERCIAL_len = 32400; 
	public static final int CA_COMMERCIAL_offset = factory.getOffset();

	/** <pre>
	           07 CA-B-Address         PIC X(255). </pre> */
	protected static final StringField CA_B_ADDRESS = factory.getStringField(255);

	/** <pre>
	           07 CA-B-Postcode        PIC X(8). </pre> */
	protected static final StringField CA_B_POSTCODE = factory.getStringField(8);

	/** <pre>
	           07 CA-B-Latitude        PIC X(11). </pre> */
	protected static final StringField CA_B_LATITUDE = factory.getStringField(11);

	/** <pre>
	           07 CA-B-Longitude       PIC X(11). </pre> */
	protected static final StringField CA_B_LONGITUDE = factory.getStringField(11);

	/** <pre>
	           07 CA-B-Customer        PIC X(255). </pre> */
	protected static final StringField CA_B_CUSTOMER = factory.getStringField(255);

	/** <pre>
	           07 CA-B-PropType        PIC X(255). </pre> */
	protected static final StringField CA_B_PROPTYPE = factory.getStringField(255);

	/** <pre>
	           07 CA-B-FirePeril       PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_FIREPERIL = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-B-FirePremium     PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_FIREPREMIUM = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-B-CrimePeril      PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_CRIMEPERIL = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-B-CrimePremium    PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_CRIMEPREMIUM = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-B-FloodPeril      PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_FLOODPERIL = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-B-FloodPremium    PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_FLOODPREMIUM = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-B-WeatherPeril    PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_WEATHERPERIL = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-B-WeatherPremium  PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_WEATHERPREMIUM = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-B-Status          PIC 9(4). </pre> */
	protected static final ExternalDecimalAsIntField CA_B_STATUS = factory.getExternalDecimalAsIntField(4, false, false, false, false);

	/** <pre>
	           07 CA-B-RejectReason    PIC X(255). </pre> */
	protected static final StringField CA_B_REJECTREASON = factory.getStringField(255);

	/** <pre>
	           07 CA-B-FILLER          PIC X(31298). </pre> */
	protected static final StringField CA_B_FILLER = factory.getStringField(31298);
	static { factory.popOffset(); } 

	/** <pre>
	*       CLAIM policy description
	        05 CA-CLAIM      REDEFINES CA-POLICY-SPECIFIC. </pre> */
	static { factory.pushOffset(); } 
	static { factory.setOffset(CA_POLICY_SPECIFIC.getOffset()); } 
	public static final int CA_CLAIM_len = 32400; 
	public static final int CA_CLAIM_offset = factory.getOffset();

	/** <pre>
	           07 CA-C-Num             PIC 9(10). </pre> */
	protected static final ExternalDecimalAsLongField CA_C_NUM = factory.getExternalDecimalAsLongField(10, false, false, false, false);

	/** <pre>
	           07 CA-C-Date            PIC X(10). </pre> */
	protected static final StringField CA_C_DATE = factory.getStringField(10);

	/** <pre>
	           07 CA-C-Paid            PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_C_PAID = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-C-Value           PIC 9(8). </pre> */
	protected static final ExternalDecimalAsIntField CA_C_VALUE = factory.getExternalDecimalAsIntField(8, false, false, false, false);

	/** <pre>
	           07 CA-C-Cause           PIC X(255). </pre> */
	protected static final StringField CA_C_CAUSE = factory.getStringField(255);

	/** <pre>
	           07 CA-C-Observations    PIC X(255). </pre> */
	protected static final StringField CA_C_OBSERVATIONS = factory.getStringField(255);

	/** <pre>
	           07 CA-C-FILLER          PIC X(31854). </pre> */
	protected static final StringField CA_C_FILLER = factory.getStringField(31854);
	static { factory.popOffset(); } 
	static { factory.popOffset(); } 

	protected byte[] _byteBuffer;


	public GenAppCommarea (byte[] buffer) {
		this._byteBuffer = buffer;
	}

	public GenAppCommarea () {
		this._byteBuffer = new byte[DFHCOMMAREA_In__len];
	}

	public byte[] getByteBuffer() {
		return _byteBuffer;
	}


	public String getCaRequestId() {
		return CA_REQUEST_ID.getString(_byteBuffer);
	}

	public void setCaRequestId(String caRequestId) {
		CA_REQUEST_ID.putString(caRequestId, _byteBuffer);
	}

	public int getCaReturnCode() {
		return CA_RETURN_CODE.getInt(_byteBuffer);
	}

	public void setCaReturnCode(int caReturnCode) {
		CA_RETURN_CODE.putInt(caReturnCode, _byteBuffer);
	}

	public long getCaCustomerNum() {
		return CA_CUSTOMER_NUM.getLong(_byteBuffer);
	}

	public void setCaCustomerNum(long caCustomerNum) {
		CA_CUSTOMER_NUM.putLong(caCustomerNum, _byteBuffer);
	}

	public String getCaRequestSpecific() {
		return CA_REQUEST_SPECIFIC.getString(_byteBuffer);
	}

	public void setCaRequestSpecific(String caRequestSpecific) {
		CA_REQUEST_SPECIFIC.putString(caRequestSpecific, _byteBuffer);
	}

	public String getCaFirstName() {
		return CA_FIRST_NAME.getString(_byteBuffer);
	}

	public void setCaFirstName(String caFirstName) {
		CA_FIRST_NAME.putString(caFirstName, _byteBuffer);
	}

	public String getCaLastName() {
		return CA_LAST_NAME.getString(_byteBuffer);
	}

	public void setCaLastName(String caLastName) {
		CA_LAST_NAME.putString(caLastName, _byteBuffer);
	}

	public String getCaDob() {
		return CA_DOB.getString(_byteBuffer);
	}

	public void setCaDob(String caDob) {
		CA_DOB.putString(caDob, _byteBuffer);
	}

	public String getCaHouseName() {
		return CA_HOUSE_NAME.getString(_byteBuffer);
	}

	public void setCaHouseName(String caHouseName) {
		CA_HOUSE_NAME.putString(caHouseName, _byteBuffer);
	}

	public String getCaHouseNum() {
		return CA_HOUSE_NUM.getString(_byteBuffer);
	}

	public void setCaHouseNum(String caHouseNum) {
		CA_HOUSE_NUM.putString(caHouseNum, _byteBuffer);
	}

	public String getCaPostcode() {
		return CA_POSTCODE.getString(_byteBuffer);
	}

	public void setCaPostcode(String caPostcode) {
		CA_POSTCODE.putString(caPostcode, _byteBuffer);
	}

	public int getCaNumPolicies() {
		return CA_NUM_POLICIES.getInt(_byteBuffer);
	}

	public void setCaNumPolicies(int caNumPolicies) {
		CA_NUM_POLICIES.putInt(caNumPolicies, _byteBuffer);
	}

	public String getCaPhoneMobile() {
		return CA_PHONE_MOBILE.getString(_byteBuffer);
	}

	public void setCaPhoneMobile(String caPhoneMobile) {
		CA_PHONE_MOBILE.putString(caPhoneMobile, _byteBuffer);
	}

	public String getCaPhoneHome() {
		return CA_PHONE_HOME.getString(_byteBuffer);
	}

	public void setCaPhoneHome(String caPhoneHome) {
		CA_PHONE_HOME.putString(caPhoneHome, _byteBuffer);
	}

	public String getCaEmailAddress() {
		return CA_EMAIL_ADDRESS.getString(_byteBuffer);
	}

	public void setCaEmailAddress(String caEmailAddress) {
		CA_EMAIL_ADDRESS.putString(caEmailAddress, _byteBuffer);
	}

	public String getCaPolicyData() {
		return CA_POLICY_DATA.getString(_byteBuffer);
	}

	public void setCaPolicyData(String caPolicyData) {
		CA_POLICY_DATA.putString(caPolicyData, _byteBuffer);
	}

	public String getCaCustsecrPass() {
		return CA_CUSTSECR_PASS.getString(_byteBuffer);
	}

	public void setCaCustsecrPass(String caCustsecrPass) {
		CA_CUSTSECR_PASS.putString(caCustsecrPass, _byteBuffer);
	}

	public String getCaCustsecrCount() {
		return CA_CUSTSECR_COUNT.getString(_byteBuffer);
	}

	public void setCaCustsecrCount(String caCustsecrCount) {
		CA_CUSTSECR_COUNT.putString(caCustsecrCount, _byteBuffer);
	}

	public String getCaCustsecrState() {
		return CA_CUSTSECR_STATE.getString(_byteBuffer);
	}

	public void setCaCustsecrState(String caCustsecrState) {
		CA_CUSTSECR_STATE.putString(caCustsecrState, _byteBuffer);
	}

	public String getCaCustsecrData() {
		return CA_CUSTSECR_DATA.getString(_byteBuffer);
	}

	public void setCaCustsecrData(String caCustsecrData) {
		CA_CUSTSECR_DATA.putString(caCustsecrData, _byteBuffer);
	}

	public long getCaPolicyNum() {
		return CA_POLICY_NUM.getLong(_byteBuffer);
	}

	public void setCaPolicyNum(long caPolicyNum) {
		CA_POLICY_NUM.putLong(caPolicyNum, _byteBuffer);
	}

	public String getCaIssueDate() {
		return CA_ISSUE_DATE.getString(_byteBuffer);
	}

	public void setCaIssueDate(String caIssueDate) {
		CA_ISSUE_DATE.putString(caIssueDate, _byteBuffer);
	}

	public String getCaExpiryDate() {
		return CA_EXPIRY_DATE.getString(_byteBuffer);
	}

	public void setCaExpiryDate(String caExpiryDate) {
		CA_EXPIRY_DATE.putString(caExpiryDate, _byteBuffer);
	}

	public String getCaLastchanged() {
		return CA_LASTCHANGED.getString(_byteBuffer);
	}

	public void setCaLastchanged(String caLastchanged) {
		CA_LASTCHANGED.putString(caLastchanged, _byteBuffer);
	}

	public long getCaBrokerid() {
		return CA_BROKERID.getLong(_byteBuffer);
	}

	public void setCaBrokerid(long caBrokerid) {
		CA_BROKERID.putLong(caBrokerid, _byteBuffer);
	}

	public String getCaBrokersref() {
		return CA_BROKERSREF.getString(_byteBuffer);
	}

	public void setCaBrokersref(String caBrokersref) {
		CA_BROKERSREF.putString(caBrokersref, _byteBuffer);
	}

	public int getCaPayment() {
		return CA_PAYMENT.getInt(_byteBuffer);
	}

	public void setCaPayment(int caPayment) {
		CA_PAYMENT.putInt(caPayment, _byteBuffer);
	}

	public String getCaPolicySpecific() {
		return CA_POLICY_SPECIFIC.getString(_byteBuffer);
	}

	public void setCaPolicySpecific(String caPolicySpecific) {
		CA_POLICY_SPECIFIC.putString(caPolicySpecific, _byteBuffer);
	}

	public String getCaEWithProfits() {
		return CA_E_WITH_PROFITS.getString(_byteBuffer);
	}

	public void setCaEWithProfits(String caEWithProfits) {
		CA_E_WITH_PROFITS.putString(caEWithProfits, _byteBuffer);
	}

	public String getCaEEquities() {
		return CA_E_EQUITIES.getString(_byteBuffer);
	}

	public void setCaEEquities(String caEEquities) {
		CA_E_EQUITIES.putString(caEEquities, _byteBuffer);
	}

	public String getCaEManagedFund() {
		return CA_E_MANAGED_FUND.getString(_byteBuffer);
	}

	public void setCaEManagedFund(String caEManagedFund) {
		CA_E_MANAGED_FUND.putString(caEManagedFund, _byteBuffer);
	}

	public String getCaEFundName() {
		return CA_E_FUND_NAME.getString(_byteBuffer);
	}

	public void setCaEFundName(String caEFundName) {
		CA_E_FUND_NAME.putString(caEFundName, _byteBuffer);
	}

	public int getCaETerm() {
		return CA_E_TERM.getInt(_byteBuffer);
	}

	public void setCaETerm(int caETerm) {
		CA_E_TERM.putInt(caETerm, _byteBuffer);
	}

	public int getCaESumAssured() {
		return CA_E_SUM_ASSURED.getInt(_byteBuffer);
	}

	public void setCaESumAssured(int caESumAssured) {
		CA_E_SUM_ASSURED.putInt(caESumAssured, _byteBuffer);
	}

	public String getCaELifeAssured() {
		return CA_E_LIFE_ASSURED.getString(_byteBuffer);
	}

	public void setCaELifeAssured(String caELifeAssured) {
		CA_E_LIFE_ASSURED.putString(caELifeAssured, _byteBuffer);
	}

	public String getCaEPaddingData() {
		return CA_E_PADDING_DATA.getString(_byteBuffer);
	}

	public void setCaEPaddingData(String caEPaddingData) {
		CA_E_PADDING_DATA.putString(caEPaddingData, _byteBuffer);
	}

	public String getCaHPropertyType() {
		return CA_H_PROPERTY_TYPE.getString(_byteBuffer);
	}

	public void setCaHPropertyType(String caHPropertyType) {
		CA_H_PROPERTY_TYPE.putString(caHPropertyType, _byteBuffer);
	}

	public int getCaHBedrooms() {
		return CA_H_BEDROOMS.getInt(_byteBuffer);
	}

	public void setCaHBedrooms(int caHBedrooms) {
		CA_H_BEDROOMS.putInt(caHBedrooms, _byteBuffer);
	}

	public int getCaHValue() {
		return CA_H_VALUE.getInt(_byteBuffer);
	}

	public void setCaHValue(int caHValue) {
		CA_H_VALUE.putInt(caHValue, _byteBuffer);
	}

	public String getCaHHouseName() {
		return CA_H_HOUSE_NAME.getString(_byteBuffer);
	}

	public void setCaHHouseName(String caHHouseName) {
		CA_H_HOUSE_NAME.putString(caHHouseName, _byteBuffer);
	}

	public String getCaHHouseNumber() {
		return CA_H_HOUSE_NUMBER.getString(_byteBuffer);
	}

	public void setCaHHouseNumber(String caHHouseNumber) {
		CA_H_HOUSE_NUMBER.putString(caHHouseNumber, _byteBuffer);
	}

	public String getCaHPostcode() {
		return CA_H_POSTCODE.getString(_byteBuffer);
	}

	public void setCaHPostcode(String caHPostcode) {
		CA_H_POSTCODE.putString(caHPostcode, _byteBuffer);
	}

	public String getCaHFiller() {
		return CA_H_FILLER.getString(_byteBuffer);
	}

	public void setCaHFiller(String caHFiller) {
		CA_H_FILLER.putString(caHFiller, _byteBuffer);
	}

	public String getCaMMake() {
		return CA_M_MAKE.getString(_byteBuffer);
	}

	public void setCaMMake(String caMMake) {
		CA_M_MAKE.putString(caMMake, _byteBuffer);
	}

	public String getCaMModel() {
		return CA_M_MODEL.getString(_byteBuffer);
	}

	public void setCaMModel(String caMModel) {
		CA_M_MODEL.putString(caMModel, _byteBuffer);
	}

	public int getCaMValue() {
		return CA_M_VALUE.getInt(_byteBuffer);
	}

	public void setCaMValue(int caMValue) {
		CA_M_VALUE.putInt(caMValue, _byteBuffer);
	}

	public String getCaMRegnumber() {
		return CA_M_REGNUMBER.getString(_byteBuffer);
	}

	public void setCaMRegnumber(String caMRegnumber) {
		CA_M_REGNUMBER.putString(caMRegnumber, _byteBuffer);
	}

	public String getCaMColour() {
		return CA_M_COLOUR.getString(_byteBuffer);
	}

	public void setCaMColour(String caMColour) {
		CA_M_COLOUR.putString(caMColour, _byteBuffer);
	}

	public int getCaMCc() {
		return CA_M_CC.getInt(_byteBuffer);
	}

	public void setCaMCc(int caMCc) {
		CA_M_CC.putInt(caMCc, _byteBuffer);
	}

	public String getCaMManufactured() {
		return CA_M_MANUFACTURED.getString(_byteBuffer);
	}

	public void setCaMManufactured(String caMManufactured) {
		CA_M_MANUFACTURED.putString(caMManufactured, _byteBuffer);
	}

	public int getCaMPremium() {
		return CA_M_PREMIUM.getInt(_byteBuffer);
	}

	public void setCaMPremium(int caMPremium) {
		CA_M_PREMIUM.putInt(caMPremium, _byteBuffer);
	}

	public int getCaMAccidents() {
		return CA_M_ACCIDENTS.getInt(_byteBuffer);
	}

	public void setCaMAccidents(int caMAccidents) {
		CA_M_ACCIDENTS.putInt(caMAccidents, _byteBuffer);
	}

	public String getCaMFiller() {
		return CA_M_FILLER.getString(_byteBuffer);
	}

	public void setCaMFiller(String caMFiller) {
		CA_M_FILLER.putString(caMFiller, _byteBuffer);
	}

	public String getCaBAddress() {
		return CA_B_ADDRESS.getString(_byteBuffer);
	}

	public void setCaBAddress(String caBAddress) {
		CA_B_ADDRESS.putString(caBAddress, _byteBuffer);
	}

	public String getCaBPostcode() {
		return CA_B_POSTCODE.getString(_byteBuffer);
	}

	public void setCaBPostcode(String caBPostcode) {
		CA_B_POSTCODE.putString(caBPostcode, _byteBuffer);
	}

	public String getCaBLatitude() {
		return CA_B_LATITUDE.getString(_byteBuffer);
	}

	public void setCaBLatitude(String caBLatitude) {
		CA_B_LATITUDE.putString(caBLatitude, _byteBuffer);
	}

	public String getCaBLongitude() {
		return CA_B_LONGITUDE.getString(_byteBuffer);
	}

	public void setCaBLongitude(String caBLongitude) {
		CA_B_LONGITUDE.putString(caBLongitude, _byteBuffer);
	}

	public String getCaBCustomer() {
		return CA_B_CUSTOMER.getString(_byteBuffer);
	}

	public void setCaBCustomer(String caBCustomer) {
		CA_B_CUSTOMER.putString(caBCustomer, _byteBuffer);
	}

	public String getCaBProptype() {
		return CA_B_PROPTYPE.getString(_byteBuffer);
	}

	public void setCaBProptype(String caBProptype) {
		CA_B_PROPTYPE.putString(caBProptype, _byteBuffer);
	}

	public int getCaBFireperil() {
		return CA_B_FIREPERIL.getInt(_byteBuffer);
	}

	public void setCaBFireperil(int caBFireperil) {
		CA_B_FIREPERIL.putInt(caBFireperil, _byteBuffer);
	}

	public int getCaBFirepremium() {
		return CA_B_FIREPREMIUM.getInt(_byteBuffer);
	}

	public void setCaBFirepremium(int caBFirepremium) {
		CA_B_FIREPREMIUM.putInt(caBFirepremium, _byteBuffer);
	}

	public int getCaBCrimeperil() {
		return CA_B_CRIMEPERIL.getInt(_byteBuffer);
	}

	public void setCaBCrimeperil(int caBCrimeperil) {
		CA_B_CRIMEPERIL.putInt(caBCrimeperil, _byteBuffer);
	}

	public int getCaBCrimepremium() {
		return CA_B_CRIMEPREMIUM.getInt(_byteBuffer);
	}

	public void setCaBCrimepremium(int caBCrimepremium) {
		CA_B_CRIMEPREMIUM.putInt(caBCrimepremium, _byteBuffer);
	}

	public int getCaBFloodperil() {
		return CA_B_FLOODPERIL.getInt(_byteBuffer);
	}

	public void setCaBFloodperil(int caBFloodperil) {
		CA_B_FLOODPERIL.putInt(caBFloodperil, _byteBuffer);
	}

	public int getCaBFloodpremium() {
		return CA_B_FLOODPREMIUM.getInt(_byteBuffer);
	}

	public void setCaBFloodpremium(int caBFloodpremium) {
		CA_B_FLOODPREMIUM.putInt(caBFloodpremium, _byteBuffer);
	}

	public int getCaBWeatherperil() {
		return CA_B_WEATHERPERIL.getInt(_byteBuffer);
	}

	public void setCaBWeatherperil(int caBWeatherperil) {
		CA_B_WEATHERPERIL.putInt(caBWeatherperil, _byteBuffer);
	}

	public int getCaBWeatherpremium() {
		return CA_B_WEATHERPREMIUM.getInt(_byteBuffer);
	}

	public void setCaBWeatherpremium(int caBWeatherpremium) {
		CA_B_WEATHERPREMIUM.putInt(caBWeatherpremium, _byteBuffer);
	}

	public int getCaBStatus() {
		return CA_B_STATUS.getInt(_byteBuffer);
	}

	public void setCaBStatus(int caBStatus) {
		CA_B_STATUS.putInt(caBStatus, _byteBuffer);
	}

	public String getCaBRejectreason() {
		return CA_B_REJECTREASON.getString(_byteBuffer);
	}

	public void setCaBRejectreason(String caBRejectreason) {
		CA_B_REJECTREASON.putString(caBRejectreason, _byteBuffer);
	}

	public String getCaBFiller() {
		return CA_B_FILLER.getString(_byteBuffer);
	}

	public void setCaBFiller(String caBFiller) {
		CA_B_FILLER.putString(caBFiller, _byteBuffer);
	}

	public long getCaCNum() {
		return CA_C_NUM.getLong(_byteBuffer);
	}

	public void setCaCNum(long caCNum) {
		CA_C_NUM.putLong(caCNum, _byteBuffer);
	}

	public String getCaCDate() {
		return CA_C_DATE.getString(_byteBuffer);
	}

	public void setCaCDate(String caCDate) {
		CA_C_DATE.putString(caCDate, _byteBuffer);
	}

	public int getCaCPaid() {
		return CA_C_PAID.getInt(_byteBuffer);
	}

	public void setCaCPaid(int caCPaid) {
		CA_C_PAID.putInt(caCPaid, _byteBuffer);
	}

	public int getCaCValue() {
		return CA_C_VALUE.getInt(_byteBuffer);
	}

	public void setCaCValue(int caCValue) {
		CA_C_VALUE.putInt(caCValue, _byteBuffer);
	}

	public String getCaCCause() {
		return CA_C_CAUSE.getString(_byteBuffer);
	}

	public void setCaCCause(String caCCause) {
		CA_C_CAUSE.putString(caCCause, _byteBuffer);
	}

	public String getCaCObservations() {
		return CA_C_OBSERVATIONS.getString(_byteBuffer);
	}

	public void setCaCObservations(String caCObservations) {
		CA_C_OBSERVATIONS.putString(caCObservations, _byteBuffer);
	}

	public String getCaCFiller() {
		return CA_C_FILLER.getString(_byteBuffer);
	}

	public void setCaCFiller(String caCFiller) {
		CA_C_FILLER.putString(caCFiller, _byteBuffer);
	}

}
